# Generated by Django 2.0.1 on 2018-01-23 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
        ('df_user', '0002_auto_20180121_1024'),
        ('df_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartIno',
            new_name='CartInof',
        ),
    ]
