# Generated by Django 2.0.1 on 2018-01-23 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
        ('df_user', '0002_auto_20180121_1024'),
        ('df_cart', '0002_auto_20180123_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnumber', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartinof',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='cartinof',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartInof',
        ),
    ]
